export interface BibleBook {
  abbr: string;
  fullName: string;
  chapters: number;
}

export const bibleBooks: Record<string, BibleBook> = {
  GEN: { abbr: "GEN", fullName: "Genesis", chapters: 50 },
  EX: { abbr: "EX", fullName: "Exodus", chapters: 40 },
  LEV: { abbr: "LEV", fullName: "Leviticus", chapters: 27 },
  NUM: { abbr: "NUM", fullName: "Numbers", chapters: 36 },
  DEU: { abbr: "DEU", fullName: "Deuteronomy", chapters: 34 },
  JOS: { abbr: "JOS", fullName: "Joshua", chapters: 24 },
  JDG: { abbr: "JDG", fullName: "Judges", chapters: 21 },
  RTH: { abbr: "RTH", fullName: "Ruth", chapters: 4 },
  "1SA": { abbr: "1SA", fullName: "1 Samuel", chapters: 31 },
  "2SA": { abbr: "2SA", fullName: "2 Samuel", chapters: 24 },
  "1KI": { abbr: "1KI", fullName: "1 Kings", chapters: 22 },
  "2KI": { abbr: "2KI", fullName: "2 Kings", chapters: 25 },
  "1CH": { abbr: "1CH", fullName: "1 Chronicles", chapters: 29 },
  "2CH": { abbr: "2CH", fullName: "2 Chronicles", chapters: 36 },
  EZR: { abbr: "EZR", fullName: "Ezra", chapters: 10 },
  NEH: { abbr: "NEH", fullName: "Nehemiah", chapters: 13 },
  EST: { abbr: "EST", fullName: "Esther", chapters: 10 },
  JOB: { abbr: "JOB", fullName: "Job", chapters: 42 },
  PSA: { abbr: "PSA", fullName: "Psalms", chapters: 150 },
  PRV: { abbr: "PRV", fullName: "Proverbs", chapters: 31 },
  ECC: { abbr: "ECC", fullName: "Ecclesiastes", chapters: 12 },
  SOS: { abbr: "SOS", fullName: "Song of Songs", chapters: 8 },
  ISA: { abbr: "ISA", fullName: "Isaiah", chapters: 66 },
  JER: { abbr: "JER", fullName: "Jeremiah", chapters: 52 },
  LAM: { abbr: "LAM", fullName: "Lamentations", chapters: 5 },
  EZE: { abbr: "EZE", fullName: "Ezekiel", chapters: 48 },
  DAN: { abbr: "DAN", fullName: "Daniel", chapters: 12 },
  HOS: { abbr: "HOS", fullName: "Hosea", chapters: 14 },
  JOE: { abbr: "JOE", fullName: "Joel", chapters: 3 },
  AMO: { abbr: "AMO", fullName: "Amos", chapters: 9 },
  OBD: { abbr: "OBD", fullName: "Obadiah", chapters: 1 },
  JON: { abbr: "JON", fullName: "Jonah", chapters: 4 },
  MIC: { abbr: "MIC", fullName: "Micah", chapters: 7 },
  NAH: { abbr: "NAH", fullName: "Nahum", chapters: 3 },
  HAB: { abbr: "HAB", fullName: "Habakkuk", chapters: 3 },
  ZEP: { abbr: "ZEP", fullName: "Zephaniah", chapters: 3 },
  HAG: { abbr: "HAG", fullName: "Haggai", chapters: 2 },
  ZEC: { abbr: "ZEC", fullName: "Zechariah", chapters: 14 },
  MAL: { abbr: "MAL", fullName: "Malachi", chapters: 4 },
  MAT: { abbr: "MAT", fullName: "Matthew", chapters: 28 },
  MRK: { abbr: "MRK", fullName: "Mark", chapters: 16 },
  LUK: { abbr: "LUK", fullName: "Luke", chapters: 24 },
  JN: { abbr: "JN", fullName: "John", chapters: 21 },
  ACT: { abbr: "ACT", fullName: "Acts", chapters: 28 },
  ROM: { abbr: "ROM", fullName: "Romans", chapters: 16 },
  "1CO": { abbr: "1CO", fullName: "1 Corinthians", chapters: 16 },
  "2CO": { abbr: "2CO", fullName: "2 Corinthians", chapters: 13 },
  GAL: { abbr: "GAL", fullName: "Galatians", chapters: 6 },
  EPH: { abbr: "EPH", fullName: "Ephesians", chapters: 6 },
  PHP: { abbr: "PHP", fullName: "Philippians", chapters: 4 },
  COL: { abbr: "COL", fullName: "Colossians", chapters: 4 },
  "1TH": { abbr: "1TH", fullName: "1 Thessalonians", chapters: 5 },
  "2TH": { abbr: "2TH", fullName: "2 Thessalonians", chapters: 3 },
  "1TI": { abbr: "1TI", fullName: "1 Timothy", chapters: 6 },
  "2TI": { abbr: "2TI", fullName: "2 Timothy", chapters: 4 },
  TIT: { abbr: "TIT", fullName: "Titus", chapters: 3 },
  PHM: { abbr: "PHM", fullName: "Philemon", chapters: 1 },
  HEB: { abbr: "HEB", fullName: "Hebrews", chapters: 13 },
  JAM: { abbr: "JAM", fullName: "James", chapters: 5 },
  "1PE": { abbr: "1PE", fullName: "1 Peter", chapters: 5 },
  "2PE": { abbr: "2PE", fullName: "2 Peter", chapters: 3 },
  "1JN": { abbr: "1JN", fullName: "1 John", chapters: 5 },
  "2JN": { abbr: "2JN", fullName: "2 John", chapters: 1 },
  "3JN": { abbr: "3JN", fullName: "3 John", chapters: 1 },
  "JUD": { abbr: "JUD", fullName: "Jude", chapters: 1 },
  REV: { abbr: "REV", fullName: "Revelation", chapters: 22 },
};